name: bandsintown_flutter
description: "Bandsintown package to use with bandsintown-proxy"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  http: ^1.2.1
  animated_size_and_fade: ^4.0.0
  material_symbols_icons: ^4.2719.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter: